services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672"
    networks:
      - microservicos-net

  eureka-serverbg:
    build: ./Eureka
    container_name: eureka-serverbg
    ports:
      - "8888:8888"
    networks:
      - microservicos-net

  config-serverbg:
    build: ./ConfigServer
    container_name: config-serverbg
    ports:
      - "8889:8889"
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/ViniciusHC/boardgame-config-repo
      - SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL=main
    networks:
      - microservicos-net

  boardgame-server:
    build: ./BG-service
    container_name: boardgame-server
    ports:
      - "8081:8081"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-serverbg:8889
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-serverbg:8888/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION=true
      - SPRING_SQL_INIT_MODE=always
    depends_on:
      - config-serverbg
      - eureka-serverbg
      - rabbitmq
    networks:
      - microservicos-net

  forum-server:
    build: ./forum-service
    container_name: forum-server
    ports:
      - "8082:8082"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-serverbg:8889
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-serverbg:8888/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION=true
      - SPRING_SQL_INIT_MODE=always
    depends_on:
      - config-serverbg
      - eureka-serverbg
      - rabbitmq
    networks:
      - microservicos-net

  gatewaybg:
    build: ./ApiGatewayBG
    container_name: gatewaybg
    ports:
      - "8085:8085"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-serverbg:8889
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-serverbg:8888/eureka/
    depends_on:
      - config-serverbg
      - eureka-serverbg
    networks:
      - microservicos-net

networks:
  microservicos-net:
    driver: bridge